/* Ações conectadas à API local: ponto, notificações, busca, folha, reajustes e solicitações. */
function functionalTimePage(){return `<div class="main-page"><div class="page-top"><div><h2>Meu ponto</h2><p>Registre e acompanhe sua jornada em tempo real.</p></div></div><div id="timeWorkspace" class="card empty">Carregando registros…</div><div id="timeHistory" class="card mt-20 empty">Carregando histórico…</div></div>`}
async function loadTimeWorkspace(){const holder=$('#timeWorkspace');if(!holder)return;try{const data=await api('/api/time/me');holder.className='card';holder.innerHTML=`<div class="card-title"><h3>Registros de hoje</h3><small class="muted-text">${data.events.length} evento(s) registrado(s)</small></div><button class="primary" data-action="punchTime">${data.nextAction}</button><div class="timeline">${data.events.map(event=>`<div><strong>${event.at}</strong><span>${event.type}</span></div>`).join('')||'<p class="muted-text">Nenhum registro de ponto hoje.</p>'}</div>`}catch(error){holder.textContent=error.message}loadTimeHistory()}
async function loadTimeHistory(){const holder=$('#timeHistory');if(!holder||!sessionUser)return;try{const data=await api(`/api/users/${sessionUser.id}/time`);holder.className='card';holder.innerHTML=`<div class="card-title"><h3>Histórico e banco de horas</h3><span class="badge ${data.bank.startsWith('-')?'no':'ok'}">${apiEscape(data.bank)}</span></div>${data.days.map(day=>`<div class="request-row"><div class="request-info"><strong>${formatDate(day.date)}</strong><span>${Math.floor(day.workedMinutes/60)}h${String(day.workedMinutes%60).padStart(2,'0')} trabalhadas · ${day.events.length} registro(s)</span></div></div>`).join('')||'<p class="muted-text">Nenhum registro de ponto ainda.</p>'}`}catch(error){holder.textContent=error.message}}
async function punchTime(){try{await api('/api/time/punch',{method:'POST',body:'{}'});loadTimeWorkspace()}catch(error){toast(error.message,'error')}}
function functionalPayrollPage(){return `<div class="main-page"><div class="page-top"><div><h2>Folha de pagamento</h2><p>Consulte sua remuneração e o agendamento de fechamento.</p></div></div><div id="payrollWorkspace" class="card empty">Carregando folha…</div><div id="payrollHistory" class="card mt-20 empty">Carregando histórico…</div></div>`}
async function loadPayrollWorkspace(){const holder=$('#payrollWorkspace');if(!holder)return;try{const [portal,scheduleData]=await Promise.all([api('/api/portal'),api('/api/payroll/close-schedule')]);const p=portal.payroll,s=scheduleData.schedule;holder.className='card';holder.innerHTML=`<div class="card-title"><h3>Minha competência ${p.competence}</h3><span class="badge ok">Disponível</span></div><section class="stats stats-3"><div class="stat"><div class="stat-top">Salário base</div><h3>${money(p.baseSalary)}</h3></div><div class="stat"><div class="stat-top">Proventos</div><h3>${money(p.earnings)}</h3></div><div class="stat"><div class="stat-top">Descontos</div><h3>${money(p.discounts)}</h3></div></section><div class="schedule-box"><div><strong>Fechamento da folha</strong><span>${s.status}${s.scheduledAt?` · ${new Date(s.scheduledAt).toLocaleString('pt-BR')} · ${apiEscape(s.scheduledBy)}`:''}</span></div><div class="actions">${scheduleData.canSchedule?'<button class="secondary" data-action="openPayrollSchedule">Programar fechamento</button>':''}<button class="primary" data-action="openPayslipView">Ver holerite</button></div></div>`}catch(error){holder.textContent=error.message}loadPayrollHistory()}
async function loadPayrollHistory(){const holder=$('#payrollHistory');if(!holder)return;try{const {history}=await api('/api/payroll/history');holder.className='card';holder.innerHTML=`<div class="card-title"><h3>Histórico de fechamentos</h3></div>${history.map(item=>`<div class="request-row"><div class="request-info"><strong>Competência ${apiEscape(item.competence)}</strong><span>Fechado em ${new Date(item.scheduledAt).toLocaleString('pt-BR')} por ${apiEscape(item.scheduledBy)}</span></div></div>`).join('')||'<p class="muted-text">Nenhum fechamento registrado ainda.</p>'}`}catch(error){holder.textContent=error.message}}
async function openPayslipView(){try{const data=await api('/api/portal');const net=data.payroll.baseSalary+data.payroll.earnings-data.payroll.discounts;$('#pageContent').innerHTML=`<div class="main-page"><div class="printable-payslip"><h2>Holerite — ${apiEscape(data.payroll.competence)}</h2><p>${apiEscape(data.user.name)} · ${apiEscape(data.user.enrollment)} · ${apiEscape(data.user.jobTitle)}</p><table><tbody><tr><td>Salário base</td><td>${money(data.payroll.baseSalary)}</td></tr><tr><td>Proventos</td><td>${money(data.payroll.earnings)}</td></tr><tr><td>Descontos</td><td>-${money(data.payroll.discounts)}</td></tr><tr><td><strong>Líquido</strong></td><td><strong>${money(net)}</strong></td></tr></tbody></table></div><div class="form-actions"><button class="secondary" data-action="go" data-args='["payroll"]'>Voltar</button><button class="primary" data-action="printPayslip">Imprimir</button></div></div>`}catch(error){toast(error.message,'error')}}
function printPayslip(){window.print()}
function openPayrollSchedule(){const markup='<div class="modal-backdrop"><div class="modal"><h2>Programar fechamento</h2><p>Esta ação é exclusiva da Tesouraria.</p><form id="scheduleForm"><label>Competência<input name="competence" value="07/2026" required></label><label>Data e hora do fechamento<input name="scheduledAt" type="datetime-local" required></label><div class="form-actions"><button type="button" class="secondary" data-action="closeModal">Cancelar</button><button class="primary">Programar</button></div></form></div></div>';
$('#modalRoot').innerHTML=markup;$('#scheduleForm').onsubmit=async event=>{event.preventDefault();try{await api('/api/payroll/close-schedule',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});closeModal();loadPayrollWorkspace()}catch(error){toast(error.message,'error')}}}

function requestsPage(){return `<div class="main-page"><div class="page-top"><div><h2>Aprovações</h2><p>Ponto, férias, horas extras, alteração cadastral e reajustes salariais.</p></div><div class="action-row"><button class="secondary" data-action="openRequestModal">+ Nova solicitação</button>${['Admin','RH','Manager'].includes(sessionUser?.role)?'<button class="primary" data-action="openSalaryModal">+ Solicitar reajuste</button>':''}</div></div><div id="requestsList" class="card table-card"><div class="empty">Carregando solicitações…</div></div></div>`}

async function loadRequests(){
  const holder=$('#requestsList');
  if(!holder)return;
  try{
    const [salary,general]=await Promise.all([api('/api/salary-requests'),api('/api/requests')]);
    const salaryRows=salary.requests.map(request=>({name:request.employeeName,type:'Alteração salarial',detail:`${money(request.oldSalary)} → ${money(request.newSalary)}`,status:request.status,statusTitle:'',action:(request.stage==='manager'&&sessionUser?.role==='Manager')||(request.stage==='cfo'&&sessionUser?.role==='CFO')?`<button class="small-btn" data-action="approveSalaryRequest" data-args='${dataArgs([request.id])}'>Confirmar</button>`:'—'}));
    const generalRows=general.requests.map(request=>({name:request.employeeName,type:request.type,detail:request.days?`${apiEscape(request.detail)} · ${request.days} dia(s)`:request.detail,status:request.status,statusTitle:request.decisionReason?`Motivo: ${request.decisionReason}`:'',action:request.status==='Pendente'&&['Admin','RH','Manager'].includes(sessionUser?.role)?`<div class="actions"><button class="small-btn" data-action="decideRequest" data-args='${dataArgs([request.id,'Aprovado'])}'>Aprovar</button><button class="small-btn reject" data-action="openRejectModal" data-args='${dataArgs([request.id])}'>Recusar</button></div>`:'—'}));
    const rows=[...generalRows,...salaryRows];
    holder.innerHTML=`<table><thead><tr><th>SOLICITANTE</th><th>TIPO</th><th>DETALHES</th><th>SITUAÇÃO</th><th>AÇÕES</th></tr></thead><tbody>${rows.map(row=>`<tr><td><div class="employee-cell">${avatar({name:row.name,initials:initials(row.name)})}${apiEscape(row.name)}</div></td><td>${apiEscape(row.type)}</td><td>${apiEscape(row.detail)}</td><td><span class="badge ${row.status==='Aprovado'?'ok':row.status==='Rejeitado'?'no':''}" title="${apiEscape(row.statusTitle||'')}">${apiEscape(row.status)}</span></td><td>${row.action}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhuma solicitação.</td></tr>'}</tbody></table>`;
    setRequestBadge(salary.requests,general.requests);
  }catch(error){holder.innerHTML=`<div class="empty">${apiEscape(error.message)}</div>`}
}

function setRequestBadge(salaryRequests,generalRequests){
  const badge=$('#requestBadge');
  if(!badge)return;
  const pendingSalary=(salaryRequests||[]).filter(request=>!['Aprovado','Rejeitado'].includes(request.status)).length;
  const pendingGeneral=(generalRequests||[]).filter(request=>request.status==='Pendente').length;
  badge.textContent=pendingSalary+pendingGeneral;
}
async function refreshRequestBadge(){try{const [salary,general]=await Promise.all([api('/api/salary-requests'),api('/api/requests')]);setRequestBadge(salary.requests,general.requests)}catch(error){}}

function openRequestModal(){
  $('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Nova solicitação</h2><p>Registre uma solicitação para o fluxo de aprovação.</p><form id="genericRequestForm"><label>Tipo de solicitação<select name="type" data-onchange="toggleVacationDaysField"><option>Ajuste de ponto</option><option>Solicitação de férias</option><option>Hora extra</option><option>Alteração cadastral</option></select></label><label id="vacationDaysField" class="hidden">Dias de férias<input name="days" type="number" min="1"></label><label>Detalhes<input name="detail" required placeholder="Descreva brevemente a solicitação"></label><div class="form-actions"><button type="button" class="secondary" data-action="closeModal">Cancelar</button><button class="primary">Enviar para aprovação</button></div></form></div></div>`;
  $('#genericRequestForm').onsubmit=async event=>{event.preventDefault();try{await api('/api/requests',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});closeModal();go('requests')}catch(error){toast(error.message,'error')}};
}
function toggleVacationDaysField(value){const field=$('#vacationDaysField');if(!field)return;const isVacation=value==='Solicitação de férias';field.classList.toggle('hidden',!isVacation);field.querySelector('input').required=isVacation}
async function decideRequest(id,status){try{await api(`/api/requests/${id}/decide`,{method:'POST',body:JSON.stringify({status})});loadRequests()}catch(error){toast(error.message,'error')}}
function openRejectModal(id){
  $('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Recusar solicitação</h2><p>Informe o motivo da recusa; ele será enviado ao solicitante.</p><form id="rejectForm"><label>Motivo<input name="reason" required placeholder="Ex.: período já coberto por outro colaborador"></label><div class="form-actions"><button type="button" class="secondary" data-action="closeModal">Cancelar</button><button class="primary">Confirmar recusa</button></div></form></div></div>`;
  $('#rejectForm').onsubmit=async event=>{event.preventDefault();try{const {reason}=Object.fromEntries(new FormData(event.target));await api(`/api/requests/${id}/decide`,{method:'POST',body:JSON.stringify({status:'Rejeitado',reason})});closeModal();loadRequests()}catch(error){toast(error.message,'error')}};
}

async function openSalaryModal(employeeId){try{const people=await documentPeople();$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Solicitar reajuste</h2><p>A alteração é aplicada somente após aprovação do gerente e CFO.</p><form id="backendSalaryForm"><label>Colaborador<select name="employeeId">${people.map(person=>`<option value="${person.id}" ${person.id===employeeId?'selected':''}>${apiEscape(person.name)}</option>`).join('')}</select></label><div class="form-grid"><label>Novo salário<input type="number" name="newSalary" min="1" step="0.01" required></label><label>Vigência<input name="effectiveDate" type="date" required></label></div><label>Motivo<input name="reason" required placeholder="Ex.: revisão anual"></label><div class="form-actions"><button type="button" class="secondary" data-action="closeModal">Cancelar</button><button class="primary">Enviar</button></div></form></div></div>`;$('#backendSalaryForm').onsubmit=async event=>{event.preventDefault();try{await api('/api/salary-requests',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});closeModal();go('requests')}catch(error){toast(error.message,'error')}}}catch(error){toast(error.message,'error')}}
async function approveSalaryRequest(id){try{await api(`/api/salary-requests/${id}/approve`,{method:'POST',body:'{}'});loadRequests()}catch(error){toast(error.message,'error')}}
function openNotifications(){api('/api/notifications').then(data=>{$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Notificações</h2>${data.notifications.map(note=>`<div class="request-row"><div class="person-avatar">!</div><div class="request-info"><strong>${apiEscape(note.title)}</strong><span>${apiEscape(note.text)}</span></div><span class="badge ${note.read?'ok':''}">${note.read?'Lida':'Nova'}</span></div>`).join('')}<div class="form-actions"><button class="secondary" data-action="markNotificationsRead">Marcar como lidas</button><button class="primary" data-action="closeModal">Fechar</button></div></div></div>`}).catch(error=>toast(error.message,'error'))}
async function markNotificationsRead(){await api('/api/notifications/read',{method:'POST',body:'{}'});closeModal();document.querySelector('.notification i')?.remove()}
function openSearch(){
  $('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Buscar colaborador</h2><p>Busque por nome ou matrícula.</p><form id="searchForm"><label>Termo de busca<input name="q" required placeholder="Ex.: Lucas ou MAT-000004"></label><div class="form-actions"><button type="button" class="secondary" data-action="closeModal">Cancelar</button><button class="primary">Buscar</button></div></form><div id="searchResults"></div></div></div>`;
  $('#searchForm').onsubmit=async event=>{
    event.preventDefault();
    const query=new FormData(event.target).get('q');
    const resultsHolder=$('#searchResults');
    resultsHolder.innerHTML='<p class="muted-text">Buscando…</p>';
    try{
      const data=await api(`/api/search?q=${encodeURIComponent(query)}`);
      resultsHolder.innerHTML=data.results.map(person=>`<div class="request-row">${avatar({name:person.name,initials:initials(person.name)})}<div class="request-info"><strong>${apiEscape(person.name)}</strong><span>${apiEscape(person.jobTitle)} · ${apiEscape(person.enrollment)}</span></div></div>`).join('')||'<p class="muted-text">Nenhum resultado encontrado.</p>';
    }catch(error){resultsHolder.innerHTML=`<p class="muted-text">${apiEscape(error.message)}</p>`}
  };
}
pages.time=functionalTimePage;pages.payroll=functionalPayrollPage;pages.requests=requestsPage;
const priorApplySessionForBadge=window.applySession;window.applySession=function(user){priorApplySessionForBadge(user);refreshRequestBadge()};
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('.notification').onclick=openNotifications;document.querySelector('.header-actions .icon-btn:first-child').onclick=openSearch;document.addEventListener('page:show',event=>{const page=event.detail;setTimeout(()=>{if(page==='time')loadTimeWorkspace();if(page==='payroll')loadPayrollWorkspace();if(page==='requests')loadRequests()},0)})});
