/* Experiência restrita para colaborador e visão de documentos por pessoa. */
const fullDashboard=pages.dashboard,fullPayroll=pages.payroll,fullTime=pages.time;
const limitedRole=()=>['Funcionário','Manager','CFO'].includes(sessionUser?.role);
function documentPeople(){if(['Admin','RH'].includes(sessionUser?.role))return api('/api/users').then(data=>data.users);return api('/api/portal').then(data=>[data.user,...data.team])}
function documentsByPersonPage(){return `<div class="main-page"><div class="page-top"><div><h2>Documentos</h2><p>Selecione um colaborador para consultar documentos enviados e pendências.</p></div>${['Admin','RH'].includes(sessionUser?.role)?'<button class="primary" data-action="openDocumentModal">+ Adicionar documento</button>':''}</div><div id="documentPeople" class="people-grid"><div class="card empty">Carregando colaboradores…</div></div></div>`}
async function loadDocumentPeople(){const holder=$('#documentPeople');if(!holder)return;try{const people=await documentPeople();holder.innerHTML=people.map(person=>`<button class="person-card" data-action="openEmployeeDocuments" data-args='${dataArgs([person.id])}'>${avatar({name:person.name,initials:initials(person.name)})}<strong>${apiEscape(person.name)}</strong><span>${apiEscape(person.jobTitle)} · ${apiEscape(person.department)}</span><small>Ver documentos e pendências →</small></button>`).join('')||'<div class="card empty">Nenhum colaborador disponível.</div>'}catch(error){holder.innerHTML=`<div class="card empty">${apiEscape(error.message)}</div>`}}
async function openEmployeeDocuments(userId){try{const data=await api(`/api/users/${userId}/documents`);const sent=data.documents.map(doc=>{const canSign=!doc.signed&&(['Admin','RH'].includes(sessionUser?.role)||doc.userId===sessionUser?.id);const signature=doc.signed?`<span class="badge ok" title="${apiEscape(doc.signedBy)}">Assinado</span>`:'<span class="badge">Pendente</span>';return `<div class="request-row"><div class="person-avatar">▤</div><div class="request-info"><strong>${apiEscape(doc.name)}</strong><span>${apiEscape(doc.category)} · versão ${doc.version} · ${apiEscape(doc.access)}</span></div>${signature}${doc.hasFile?`<button class="link-button" data-action="downloadDocument" data-args='${dataArgs([doc.id,doc.name])}'>Baixar</button>`:''}${canSign?`<button class="link-button" data-action="signDocument" data-args='${dataArgs([doc.id,userId])}'>Assinar</button>`:''}</div>`}).join('')||'<p class="muted-text">Nenhum documento enviado.</p>';const pending=data.pending.map(item=>`<div class="request-row"><div class="person-avatar">!</div><div class="request-info"><strong>${apiEscape(item)}</strong><span>Documento obrigatório ainda não localizado</span></div><span class="badge">Pendente</span></div>`).join('')||'<p class="success-text">Todos os documentos obrigatórios foram localizados.</p>';$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal documents-modal"><h2>${apiEscape(data.user.name)}</h2><p>${apiEscape(data.user.enrollment)} · Documentação do colaborador</p><h3>Enviados</h3>${sent}<h3 class="mt-20">Pendentes</h3>${pending}<div class="form-actions"><button class="primary" data-action="closeModal">Fechar</button></div></div></div>`}catch(error){toast(error.message,'error')}}
function restrictedDashboard(){return `<div class="main-page"><div class="page-top"><div><h2>Meu espaço</h2><p>Informações pessoais, jornada e, quando aplicável, seu time.</p></div></div><div id="portalView" class="card empty">Carregando informações…</div></div>`}
async function loadPortal(){const holder=$('#portalView');if(!holder)return;try{const data=await api('/api/portal'),net=data.payroll.baseSalary+data.payroll.earnings-data.payroll.discounts;holder.className='';holder.innerHTML=`<section class="stats stats-5"><div class="stat"><div class="stat-top">Meu salário base</div><h3>${money(data.payroll.baseSalary)}</h3><small>Competência ${data.payroll.competence}</small></div><div class="stat"><div class="stat-top">Líquido estimado</div><h3>${money(net)}</h3><small>Uso pessoal</small></div><div class="stat"><div class="stat-top">Jornada hoje</div><h3>${data.time.worked}</h3><small>${data.time.status}</small></div><div class="stat"><div class="stat-top">Banco de horas</div><h3>${data.time.bank}</h3><small>Saldo atual</small></div><div class="stat"><div class="stat-top">Saldo de férias</div><h3>${data.vacationBalance} dias</h3><small>Disponível para solicitação</small></div></section>${data.benefits.length?`<div class="card mt-20"><div class="card-title"><h3>Meus benefícios</h3></div>${data.benefits.map(benefit=>`<div class="request-row"><div class="request-info"><strong>${apiEscape(benefit.name)}</strong><span>${money(benefit.value)}/mês</span></div></div>`).join('')}</div>`:''}${data.team.length?`<div class="card mt-20"><div class="card-title"><h3>Meu time</h3><span class="count-label">${data.team.length} pessoa(s)</span></div>${data.team.map(person=>`<div class="request-row">${avatar({name:person.name,initials:initials(person.name)})}<div class="request-info"><strong>${apiEscape(person.name)}</strong><span>${apiEscape(person.jobTitle)} · ${apiEscape(person.department)}</span></div><button class="link-button" data-action="openEmployeeDocuments" data-args='${dataArgs([person.id])}'>Documentos</button></div>`).join('')}</div>`:''}`}catch(error){holder.className='card empty';holder.textContent=error.message}}
pages.dashboard=()=>limitedRole()?restrictedDashboard():fullDashboard();pages.payroll=fullPayroll;pages.time=fullTime;pages.documents=documentsByPersonPage;
const priorSession=window.applySession;window.applySession=function(user){priorSession(user);const adminOrRh=['Admin','RH'].includes(user?.role);document.querySelector('[data-page="employees"]')?.classList.toggle('hidden',!adminOrRh);document.querySelector('[data-page="organograma"]')?.classList.toggle('hidden',!adminOrRh);};
document.addEventListener('DOMContentLoaded',()=>{if(location.protocol==='file:'){const note=document.createElement('div');note.className='file-warning';note.textContent='Para usar todos os recursos, inicie o servidor e abra http://localhost:4173.';$('.demo-note').after(note)}document.addEventListener('page:show',event=>{const page=event.detail;setTimeout(()=>{if(page==='documents')loadDocumentPeople();if(limitedRole()&&page==='dashboard')loadPortal()},0)})});
